from django.contrib.auth import views as auth_views
from django.urls import path

from .views import (
    AdminDashboardView,
    AdminLandlordListView,
    AdminRoomListView,
    AdminTenantListView,
    RoomBookingDashboardView,
    RoomCreateView,
    RoomDashboardListView,
    RoomDeleteView,
    RoomUpdateView,
    TenantBookingListView,
    add_review,
    approve_booking,
    book_room,
    cancel_my_booking,
    create_room,
    home_page,
    login_user,
    login_view,
    logout_view,
    profile_view,
    public_home_page,
    register_user,
    register_view,
    reject_booking,
    room_detail,
)

app_name = "phongtro"

urlpatterns = [
    path("", home_page, name="home_page"),
    path("danh-sach-phong/", public_home_page, name="public_home_page"),
    path("profile/", profile_view, name="profile"),
    path("rooms/<int:room_id>/", room_detail, name="room_detail"),
    path("rooms/<int:room_id>/review/", add_review, name="add_review"),
    path("rooms/<int:room_id>/book/", book_room, name="book_room"),
    path("my-bookings/", TenantBookingListView.as_view(), name="my_bookings"),
    path("my-bookings/<int:booking_id>/cancel/", cancel_my_booking, name="cancel_my_booking"),
    path("login-user/", login_user, name="login_user"),
    path("login/", login_view, name="login"),
    path("register-user/", register_user, name="register_user"),
    path("register/", register_view, name="register"),
    path(
        "password-reset/",
        auth_views.PasswordResetView.as_view(template_name="registration/password_reset_form.html"),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(template_name="registration/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(template_name="registration/password_reset_confirm.html"),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(template_name="registration/password_reset_complete.html"),
        name="password_reset_complete",
    ),
    path("logout/", logout_view, name="logout"),
    path("rooms/create/", create_room, name="create_room"),
    path("dashboard/", RoomDashboardListView.as_view(), name="dashboard"),
    path("system-admin/", AdminDashboardView.as_view(), name="admin_dashboard"),
    path("system-admin/landlords/", AdminLandlordListView.as_view(), name="admin_landlords"),
    path("system-admin/tenants/", AdminTenantListView.as_view(), name="admin_tenants"),
    path("system-admin/rooms/", AdminRoomListView.as_view(), name="admin_rooms"),
    path("dashboard/bookings/", RoomBookingDashboardView.as_view(), name="dashboard_bookings"),
    path("dashboard/bookings/<int:booking_id>/approve/", approve_booking, name="approve_booking"),
    path("dashboard/bookings/<int:booking_id>/reject/", reject_booking, name="reject_booking"),
    path("dashboard/add/", RoomCreateView.as_view(), name="dashboard_add"),
    path("dashboard/edit/<int:pk>/", RoomUpdateView.as_view(), name="dashboard_edit"),
    path("dashboard/delete/<int:pk>/", RoomDeleteView.as_view(), name="dashboard_delete"),
]
