# Generated by Django 5.2.11 on 2026-02-19 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HopDong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_bat_dau', models.DateField()),
                ('ngay_ket_thuc', models.DateField()),
                ('trang_thai', models.CharField(default='Hiệu lực', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LoaiPhong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_loai', models.CharField(max_length=100)),
                ('don_gia', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='NguoiThue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=100)),
                ('cccd', models.CharField(max_length=20)),
                ('so_dien_thoai', models.CharField(max_length=15)),
                ('dia_chi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thang', models.CharField(max_length=20)),
                ('tien_phong', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tien_dien', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tien_nuoc', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tong_tien', models.DecimalField(decimal_places=2, max_digits=12)),
                ('da_thanh_toan', models.BooleanField(default=False)),
                ('hop_dong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phongtro.hopdong')),
            ],
        ),
        migrations.AddField(
            model_name='hopdong',
            name='nguoi_thue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phongtro.nguoithue'),
        ),
        migrations.CreateModel(
            name='Phong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_phong', models.CharField(max_length=10)),
                ('trang_thai', models.CharField(default='Trống', max_length=50)),
                ('loai_phong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phongtro.loaiphong')),
            ],
        ),
        migrations.AddField(
            model_name='hopdong',
            name='phong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phongtro.phong'),
        ),
    ]
