# Generated by Django 5.2.11 on 2026-03-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phongtro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hopdong',
            name='nguoi_thue',
        ),
        migrations.RemoveField(
            model_name='hopdong',
            name='phong',
        ),
        migrations.RemoveField(
            model_name='phong',
            name='loai_phong',
        ),
        migrations.RemoveField(
            model_name='phong',
            name='so_phong',
        ),
        migrations.AddField(
            model_name='phong',
            name='dien_tich',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='phong',
            name='gia',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='phong',
            name='mo_ta',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='phong',
            name='ten_phong',
            field=models.CharField(default='Phong moi', max_length=100),
        ),
        migrations.AlterField(
            model_name='phong',
            name='trang_thai',
            field=models.CharField(choices=[('trong', 'Trong'), ('da_thue', 'Da thue'), ('bao_tri', 'Bao tri')], default='trong', max_length=20),
        ),
        migrations.DeleteModel(
            name='HoaDon',
        ),
        migrations.DeleteModel(
            name='NguoiThue',
        ),
        migrations.DeleteModel(
            name='HopDong',
        ),
        migrations.DeleteModel(
            name='LoaiPhong',
        ),
    ]
