# Generated by Django 5.2.11 on 2026-03-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phongtro', '0002_remove_hopdong_nguoi_thue_remove_hopdong_phong_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phong',
            name='khu_vuc',
            field=models.CharField(default='Thai Nguyen', max_length=120),
        ),
    ]
