#Generated by Django 5.2.11 on 2026-03-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phongtro', '0003_phong_khu_vuc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phong',
            name='dien_tich',
        ),
        migrations.RemoveField(
            model_name='phong',
            name='gia',
        ),
        migrations.RemoveField(
            model_name='phong',
            name='khu_vuc',
        ),
        migrations.RemoveField(
            model_name='phong',
            name='mo_ta',
        ),
        migrations.RemoveField(
            model_name='phong',
            name='ten_phong',
        ),
        migrations.RemoveField(
            model_name='phong',
            name='trang_thai',
        ),
        migrations.AddField(
            model_name='phong',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='phong',
            name='area',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='phong',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='rooms/'),
        ),
        migrations.AddField(
            model_name='phong',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='phong',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='phong',
            name='room_type',
            field=models.CharField(default='Phong tro thuong', max_length=100),
        ),
        migrations.AddField(
            model_name='phong',
            name='title',
            field=models.CharField(default='Phong moi', max_length=200),
        ),
    ]
