#Generated by Django 5.2.11 on 2026-3-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phongtro', '0004_remove_phong_dien_tich_remove_phong_gia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phong',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='phong',
            name='owner_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
