# Generated by Django 5.2.11 on 2026-03-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phongtro', '0010_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='phong',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='phong',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
